services:
  backend:
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

include:
  - ./external-services/n8n/compose.yaml
  - ./external-services/lavalink/compose.yaml
